config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources 'articles'
  root 'welcomes#index'
  resources 'contacts', only: [:new, :create]

  get '*path' => redirect('/') unless Rails.env.development?

end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Miguel",
      :to => "neneriostb@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only:[:new,:edit,:create,:update,:destroy]
  before_action :article_find, only: [:show, :edit,:update, :destroy]


  def index
    @articles = Article.all.order('created_at DESC').paginate(:page => params[:page],  :per_page => 10)
  end

  def new
    @article= Article.new
  end

  def create
    @article= Article.create(params_article)
    if @article.save
      redirect_to @article
    end
  end

  def show
  end

  def edit

  end

  def update
    @article.update_attributes(params_article)
    if @article.save
      redirect_to @article
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

  def params_article
    params.require(:article).permit(:title, :description,:slug)
  end

  def article_find
    @article= Article.friendly.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact= Contact.new
  end
  def create
    @contact_form = Contact.new(params[:contact])
    @contact_form.request = request
    if @contact_form.deliver
      flash.now[:error]=nil
    else
      flash.now[:error]= "can't send message"
      render new
    end
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
    @articles= Article.all.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # create a custom renderer that allows highlighting of code blocks
class HTMLwithPygments < Redcarpet::Render::HTML
  def block_code(code, language)
    Pygments.highlight(code, lexer: language)
  end
end


  def markdown(content)
    renderer = HTMLwithPygments.new(filter_html: true, hard_wrap: true)
    options={
      superscript: true,
      strikethrough: true,
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      autolink: true,
      lax_html_blocks: true,
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/articles/_form.html.erb
<div class="form">
  <%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@article.errors.count, "error") %>.
    </div>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <%= f.label :Title, 'Title' %>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :Description, "Description" %>
      <%= f.text_area :description %>
    </div>
    <div class="form-group">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1 id="principal_title">Edit Article</h1>
<div class="wrapper_general wrapper_padding">
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<h1 id="principal_title">Articles</h1>
<div class="wrapper_general wrapper_padding">
<% @articles.each do |article| %>
  <div class="title">
  <%= link_to article.title, article_path(article)  %>
  </div>
  <div class="date">
    <%= article.created_at.strftime('%A %B %d') %>
  </div>
  <hr>
<% end %>
<% if user_signed_in? %>
<%= link_to 'New Article', new_article_path, id:"form_buttom"  %>
<% end %>
<%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1 id="principal_title">New Article</h1>
<div class="wrapper_general wrapper_padding">
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container_article">
  <p class="data"><%= @article.created_at.strftime("%A, %b %d") %></p>
  <h1><%= @article.title %></h1>
  <hr>
  <div class="content">
    <%= markdown( @article.description) %>
  </div>
  <% if user_signed_in? %>
  <div id="actions">
    <%= link_to "edit", edit_article_path(@article) %>

    <%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "deseas eliminar"} %>
  </div>
  <% end %>
  <hr>
  <div id="share_box">
    <p>Share Article</p>
    <!-- Twitter -->
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @article.title %> by @neneriostb - &amp;url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
  </div>
  <hr>

  <div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_config = function () {
this.page.url = '<%= url_for([@article, {only_path:false }]) %>';
this.page.identifier = '<%= @article.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
this.page.title= '<%= @article.title %>';
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//mike-blog.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
</div>

app/views/contacts/create.html.erb
<h1 id="principal_title">Contact</h1>
<div class="wrapper_general wrapper_padding">
  <h3>Thanks for your message!.</h3>
</div>

app/views/contacts/new.html.erb
<h1 id="principal_title">Contact</h1>
<div class="wrapper_general wrapper_padding">
  <div class="form">
  <%= form_for @contact do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, required: true %>
    </div>
    <div class="form-group">
      <%= f.label :message, "Message" %>
      <%= f.text_area :message, as: :text %>
    </div>
    <div class="form-group">
      <%= f.text_field :nickname , type:'hidden' %>
      <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    </div>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="main_navigation" class="clearfix">
  <%= link_to 'Mike', root_path, class:"name" %>
  <nav>
    <%= link_to 'Article', articles_path %>
    <a href="#">Project</a>
    <%= link_to 'Contact', new_contact_path%>
    <% if user_signed_in? %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete  %>
      <% else %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>
  </nav>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

<footer>
  <p>
    &copy Mike
  </p>
  <nav>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
  </nav>
</footer>
</body>
</html>

app/views/welcomes/index.html.erb
<div class="wrapper clearfix wrapper_padding content_center">
  <div class="col-1">
    <h1>About</h1>
    <hr>
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem <a>sequi nesciunt</a>. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis susci</p>
  </div>
  <div class="col-2" >
    <h1>Articles</h1>
    <hr>
    <% @articles.each do |article| %>
    <p class="title">
    <%= link_to article.title, article_path(article) %>
    <a></a></p>
    <p class="data "><%= article.created_at.strftime("%A, %b %d")  %></p>
    <% end %>
  </div>

  <div class="col-3">
    <h1>Projects</h1>
    <hr>
    <p><a>Sed ut perspiciatis unde omnis iste natus</a></p>
    <p class="data">enero, 21- 2016</p>
    <p><a>Sed ut perspiciatis unde omnis iste natus</a></p>
    <p class="data">enero, 21- 2016</p>
    <p><a>Sed ut perspiciatis unde omnis iste natus</a></p>
    <p class="data">enero, 21- 2016</p>
  </div>
</div>